spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/test
      username: manager
      password: duddus186213!
      driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
